// Compiler capability entry: explicit exports from implementation modules only.
export { _$withCompiledPropsUpdater } from '../compact-component-abi'
export { _$withCompiledHookScope } from '../compact-component-abi'
export { _$mountCompiledComponent } from '../../compiled-component'
export { _$compiledOmitProps } from '../../compiled-props'
export { _$compiledPropsGet } from '../../compiled-props'
export { _$compiledPropsCall } from '../../compiled-props'
export { _$compiledPropsHas } from '../../compiled-props'
export { _$compiledPropsKeys } from '../../compiled-props'
export { _$compiledPropsSnapshot } from '../../compiled-props'
export { _$createComponent, _$createDynamicElement } from '../../compiled-component-call'
export { _$compiledComponent } from '../../compiled-component'
export { useEmit } from '../component-emit'
export { onErrorCaptured } from '../component-errors'
export type { CompiledComponentFactory, CompiledSlots } from '../component'
